export ZSH=/home/magnus/.oh-my-zsh

ZSH_THEME="agnoster"
plugins=(git go golang)

export PATH="/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl"
source $ZSH/oh-my-zsh.sh

[[ -s "/home/magnus/.gvm/scripts/gvm" ]] && source "/home/magnus/.gvm/scripts/gvm"

export GOBIN="$GOPATH/bin"
export PATH="$PATH:$HOME/.rvm/bin:$GOBIN"

export EDITOR="vim"
alias ls="ls --color -F"
