export ZSH=/home/magnus/.oh-my-zsh

ZSH_THEME="agnoster"
plugins=(git go golang)

source $ZSH/oh-my-zsh.sh	

setopt no_share_history

export PATH="/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl:$HOME/.rvm/bin"

[[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm"
[[ -s "$HOME/.gvm/scripts/gvm" ]] && source "$HOME/.gvm/scripts/gvm"

export GOBIN="$GOPATH/bin"
export EDITOR="nvim"

alias ls="ls --color -F"
alias vim="nvim"
